api:
  punkapi:
    url: https://api.punkapi.com/v2/beers

feign:
  name: auth-api
  endpoint-all: /auth-api/v1/test/all
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

spring:
  web:
    locale-resolver: accept_header
    locale: en
  application:
    name: beers-api

server:
  port: 8091

eureka:
  instance:
    appname: beers-api
  client:
    eureka-server-port: 8761
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
#      default-zone: http://eureka-server:${eureka.client.eureka-server-port}/eureka